version: '3'
services:
  blog:
    build: .
    environment:
      PASSWORD: example
      NAME: eeblog@example
    ports:
    - "8080:8080"
    links:
    - pgsql
  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: eeblog
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
